# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RAhrmTH20Jo1_m6cE7l0h8IPVhiP1vV2
"""

import requests

# Download the dataset from a public URL
url = "https://raw.githubusercontent.com/ageron/handson-ml2/master/datasets/housing/housing.tgz"
output_path = "housing.tgz"

response = requests.get(url, stream=True)
response.raise_for_status()  # Raise an exception for HTTP errors

with open(output_path, "wb") as f:
    for chunk in response.iter_content(chunk_size=8192):
        f.write(chunk)

print(f"Downloaded {output_path}")

# Verify the download
!ls -l housing.tgz

# Extract the contents of the tgz file
!tar -xzf housing.tgz

# List the contents of the extracted directory (housing) to verify
!ls -l housing/

# Create the target directory if it doesn't exist and then unzip the house price dataset
!mkdir -p "/content/house_prices_dataset"
!unzip -o "/content/house-prices-advanced-regression-techniques.zip" -d "/content/house_prices_dataset"

"""### Download Kaggle House Prices Dataset

To download the Kaggle House Prices dataset, you need to use the Kaggle API. Follow these steps:

1.  **Create a Kaggle API Token**: Go to your Kaggle account (https://www.kaggle.com/your-username/account), scroll down to the 'API' section, and click 'Create New API Token'. This will download a `kaggle.json` file.
2.  **Upload `kaggle.json`**: In the Colab environment, click on the folder icon on the left panel (Files), then click the 'Upload to session storage' icon. Upload your `kaggle.json` file.
3.  **Install Kaggle**: Run the cell below to install the Kaggle API client.
4.  **Move `kaggle.json`**: Run the next cell to move `kaggle.json` to the correct directory and set permissions.
5.  **Download Dataset**: Run the final cell to download the dataset.
"""

# Install the Kaggle API client
!pip install kaggle

# Make a directory for Kaggle configuration and move the API token
!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

# Download the House Prices - Advanced Regression Techniques dataset
!kaggle competitions download -c house-prices-advanced-regression-techniques -p /content/

# Verify if kaggle.json is in the current directory after uploading
!ls -l kaggle.json

"""Now that the dataset is downloaded, you need to unzip it into the `/content/house_prices_dataset` directory, as the original code expects it there. Run the following cell to unzip the file:"""

# Unzip the house price dataset into the specified directory
!unzip "/content/house-prices-advanced-regression-techniques.zip" -d "/content/house_prices_dataset"

"""After running the above cells, the `train.csv` file should be available at `/content/house_prices_dataset/train.csv`, and your original code cell for loading the `train.csv` will work."""

# List the contents of the extracted directory to verify
!ls -l "/content/house_prices_dataset"

# List all files in the current directory to find where 'housing.tgz' contents might have landed
!ls -l

import pandas as pd

# Load the housing.csv file
housing_df = pd.read_csv('housing.csv')

# Display the first few rows and information about the DataFrame
display(housing_df.head())
display(housing_df.info())

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Load the train.csv file from the house_prices_dataset directory
train_df = pd.read_csv('/content/house_prices_dataset/train.csv')

# Display the first few rows and information about the DataFrame to check columns
display(train_df.head())
display(train_df.info())

missing_values = train_df.isnull().sum()
missing_values = missing_values[missing_values > 0].sort_values(ascending=False)
missing_percentage = (train_df.isnull().sum() / len(train_df)) * 100
missing_percentage = missing_percentage[missing_percentage > 0].sort_values(ascending=False)

missing_info = pd.DataFrame({'Missing Count': missing_values, 'Missing Percentage': missing_percentage})
display(missing_info)

# Create a scatter plot of GrLivArea vs SalePrice
plt.figure(figsize=(10, 6))
sns.scatterplot(x='GrLivArea', y='SalePrice', data=train_df)
plt.title('Ground Living Area vs. Sale Price')
plt.xlabel('Ground Living Area (square feet)')
plt.ylabel('Sale Price')
plt.grid(True)
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

# Feature Engineering: Create TotalBaths
train_df['TotalBaths'] = train_df['FullBath'] + 0.5 * train_df['HalfBath'] + \
                         train_df['BsmtFullBath'] + 0.5 * train_df['BsmtHalfBath']

# Select features (X) and target (y)
features = ['GrLivArea', 'BedroomAbvGr', 'TotalBaths']
X = train_df[features]
y = train_df['SalePrice']

# Handle missing values (if any) - A simple strategy is to fill with the mean
# In this specific dataset, for the chosen features, there are no missing values, but it's good practice.
X = X.fillna(X.mean())

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the Linear Regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(f"Model Coefficients: {model.coef_}")
print(f"Model Intercept: {model.intercept_}")
print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")
print(f"R-squared (R2): {r2:.2f}")

plt.figure(figsize=(10, 7))
sns.scatterplot(x=y_test, y=y_pred)
plt.plot([y.min(), y.max()], [y.min(), y.max()], 'r--', lw=2) # Diagonal line for perfect prediction
plt.xlabel('Actual SalePrice')
plt.ylabel('Predicted SalePrice')
plt.title('Actual vs. Predicted SalePrice (Test Set)')
plt.grid(True)
plt.show()

# Add 'OverallQual' to the features list
new_features = ['GrLivArea', 'BedroomAbvGr', 'TotalBaths', 'OverallQual']
X_new = train_df[new_features]
y_new = train_df['SalePrice']

# Handle missing values (if any) - Fill with the mean
X_new = X_new.fillna(X_new.mean())

# Split data into training and testing sets for the new model
X_train_new, X_test_new, y_train_new, y_test_new = train_test_split(X_new, y_new, test_size=0.2, random_state=42)

# Initialize and train the new Linear Regression model
model_new = LinearRegression()
model_new.fit(X_train_new, y_train_new)

# Make predictions on the new test set
y_pred_new = model_new.predict(X_test_new)

# Evaluate the new model
mse_new = mean_squared_error(y_test_new, y_pred_new)
rmse_new = np.sqrt(mse_new)
r2_new = r2_score(y_test_new, y_pred_new)

print("--- Original Model Performance ---")
print(f"Original MSE: {mse:.2f}")
print(f"Original RMSE: {rmse:.2f}")
print(f"Original R-squared: {r2:.2f}")
print("\n--- New Model Performance (with OverallQual) ---")
print(f"New Model Coefficients: {model_new.coef_}")
print(f"New Model Intercept: {model_new.intercept_}")
print(f"New MSE: {mse_new:.2f}")
print(f"New RMSE: {rmse_new:.2f}")
print(f"New R-squared: {r2_new:.2f}")

from sklearn.model_selection import KFold, cross_val_score

# Define the features for the updated model
cv_features = ['GrLivArea', 'BedroomAbvGr', 'TotalBaths', 'OverallQual']
X_cv = train_df[cv_features]
y_cv = train_df['SalePrice']

# Handle missing values (if any) - Fill with the mean
X_cv = X_cv.fillna(X_cv.mean())

# Initialize the Linear Regression model
cv_model = LinearRegression()

# Set up K-Fold Cross-Validation
kf = KFold(n_splits=5, shuffle=True, random_state=42) # Using 5 folds

# Perform cross-validation for R-squared
r2_scores = cross_val_score(cv_model, X_cv, y_cv, cv=kf, scoring='r2')

# Perform cross-validation for Mean Squared Error (negative because cross_val_score maximizes the score)
mse_scores = -cross_val_score(cv_model, X_cv, y_cv, cv=kf, scoring='neg_mean_squared_error')
rmse_scores = np.sqrt(mse_scores)

print("\n--- Cross-Validation Results (with OverallQual) ---")
print(f"R-squared scores for each fold: {r2_scores}")
print(f"Average R-squared: {np.mean(r2_scores):.2f} (+/- {np.std(r2_scores):.2f})")
print(f"MSE scores for each fold: {mse_scores}")
print(f"Average MSE: {np.mean(mse_scores):.2f} (+/- {np.std(mse_scores):.2f})")
print(f"RMSE scores for each fold: {rmse_scores}")
print(f"Average RMSE: {np.mean(rmse_scores):.2f} (+/- {np.std(rmse_scores):.2f})")

"""Now, let's use the `model_new` (which includes 'GrLivArea', 'BedroomAbvGr', 'TotalBaths', and 'OverallQual') to predict the `SalePrice` and add these predictions as a new 'feature' (a column) to our `train_df`."""

# Define the features used by model_new
prediction_features = ['GrLivArea', 'BedroomAbvGr', 'TotalBaths', 'OverallQual']

# Ensure 'TotalBaths' is created in train_df before prediction if not already present
if 'TotalBaths' not in train_df.columns:
    train_df['TotalBaths'] = train_df['FullBath'] + 0.5 * train_df['HalfBath'] + \
                             train_df['BsmtFullBath'] + 0.5 * train_df['BsmtHalfBath']

# Prepare the data for prediction using the same features as model_new
X_predict = train_df[prediction_features]

# Handle missing values in prediction_features using the mean strategy, similar to training
X_predict = X_predict.fillna(X_predict.mean())

# Generate predictions using the trained model_new
train_df['PredictedSalePrice'] = model_new.predict(X_predict)

# Display the first few rows with the new predicted price column
display(train_df[['GrLivArea', 'BedroomAbvGr', 'TotalBaths', 'OverallQual', 'SalePrice', 'PredictedSalePrice']].head())

"""```markdown
# House Price Prediction using Linear Regression

This notebook demonstrates a basic machine learning workflow to predict house prices using a Linear Regression model. It leverages two datasets: a general housing dataset (from Hands-On Machine Learning) for initial exploration and the Ames Housing dataset (Kaggle's House Prices - Advanced Regression Techniques competition) for the primary prediction task.

## Project Overview

The goal of this project is to build and evaluate a simple linear regression model to predict the sale price of houses based on various features. The process includes:

1.  **Data Acquisition**: Downloading and extracting the necessary datasets.
2.  **Data Loading and Initial Exploration**: Loading the datasets into pandas DataFrames and performing initial checks (head, info).
3.  **Exploratory Data Analysis (EDA)**: Visualizing relationships between key features (e.g., living area vs. sale price).
4.  **Feature Engineering**: Creating new features to improve model performance (e.g., `TotalBaths`).
5.  **Model Training**: Training a Linear Regression model.
6.  **Model Evaluation**: Assessing model performance using metrics like Mean Squared Error (MSE), Root Mean Squared Error (RMSE), and R-squared. This also includes visualizing actual vs. predicted values.
7.  **Feature Improvement & Cross-Validation**: Iteratively improving the model by adding more relevant features and using K-Fold Cross-Validation for robust evaluation.

## Dataset

This project uses two datasets:

*   **Housing Dataset (Ageron's Hands-On ML)**: Used for initial demonstration of data loading (`housing.csv`).
*   **Ames Housing Dataset**: The primary dataset for house price prediction. It contains detailed information about residential homes in Ames, Iowa, and their sale prices (`train.csv` from `house-prices-advanced-regression-techniques.zip`).

## Setup and Installation

To run this notebook, you'll need the following libraries:

*   `requests`
*   `pandas`
*   `matplotlib`
*   `seaborn`
*   `scikit-learn`
*   `numpy`

You can install them using pip:

```bash
pip install requests pandas matplotlib seaborn scikit-learn numpy
```

## Usage

1.  **Clone the repository (if applicable)** or download the notebook.
2.  **Open the notebook** in Google Colab or a Jupyter environment.
3.  **Run all cells** in sequence. The notebook will automatically download and extract the required data.

### Key Steps in the Notebook:

*   **Data Download & Extraction**: Cells at the beginning handle downloading `housing.tgz` and `house-prices-advanced-regression-techniques.zip`, and extracting their contents.
*   **Load Data**: `pd.read_csv()` is used to load `housing.csv` and `train.csv`.
*   **Initial EDA**: Scatter plots visualize relationships between features and the target variable.
*   **Linear Regression Model**: A `LinearRegression` model from `sklearn.linear_model` is used.
*   **Feature Engineering**: `TotalBaths` is created as a composite feature.
*   **Model Evaluation**: `mean_squared_error`, `r2_score`, and `train_test_split` are used for evaluating the model.
*   **Cross-Validation**: `KFold` and `cross_val_score` are utilized for more robust model assessment.

## Results

The notebook demonstrates how adding relevant features (like `OverallQual`) can improve the R-squared score and reduce prediction errors. Cross-validation provides a more reliable estimate of the model's performance on unseen data.

## Future Work

*   **More Advanced Feature Engineering**: Explore creating more complex features from existing ones (e.g., interaction terms, polynomial features).
*   **Categorical Feature Handling**: Implement one-hot encoding or other techniques for categorical variables.
*   **Model Selection**: Experiment with other regression models (e.g., RandomForestRegressor, GradientBoostingRegressor).
*   **Hyperparameter Tuning**: Optimize model parameters using techniques like GridSearchCV or RandomizedSearchCV.
*   **Error Analysis**: Investigate where the model makes the largest errors to identify potential areas for improvement.
```
"""